### PR TITLE
fix #22 bug in import path type

### LINKED ISSUE #22: import-path-type treats directory with common prefix as the same module
Seems to be doing a simple starts-with check:

```javascript
// src/frontend/modules/orange/foo.js
import bar from 'src/frontend/modules/orangejuice/bar';
```

```
src\frontend\modules\orange\foo.js
  1:1   error  Path should be '../orangejuice/bar' saxo/import-path-type
```

Not a particular concern at the moment; we only have 7 instances of this in the codebase, and given their coupling they will likely soon be merged into one module.

### PR DESCRIPTION
**Pull request by lukeapage**

### CODE REVIEW

**Comment by lukeapage** [comment]
@robatwilliams can you review?

File: src/rules/import-path-type.js [hunk 1]
```diff
@@ -32,20 +32,21 @@ module.exports = {
...
                 // the base at which outside of this it should be absolute and inside it should be relative
-                const baseDir = dirName.split('/').slice(0, parts).join('/');
+                const baseDir =
+                    dirName.split('/').slice(0, parts).join('/') + '/';
 
                 const importPath = node.source.value;
-                const resolvedImportPath = importPath.startsWith('.')
-                    ? path.join(dirName, importPath).replace(/\\/g, '/')
-                    : importPath;
+                const resolvedImportPath = importPath.startsWith('.') ?
```
Comment (robatwilliams) [inline src/rules/import-path-type.js:47]: Has some non-Prettier formatter done this, along with the changes to quote marks such that they now require escaping?

**Review by robatwilliams — APPROVED** [review]

File: src/rules/import-path-type.js (hunk 1 above)
Comment (lukeapage) [reply src/rules/import-path-type.js:47]: I was formatting with prettier, but I haven't got round to setting up this project properly - so running lint-fix after prettier puts it back to requiring escaping...
